remote_theme: sergiokopplin/indigo
#theme: jekyll-theme-minimal
title: Alexia
description: "A backend dev who deserted to operations and never went back."
email: alexiarstein@aol.com
external-image: false
picture: assets/images/alexia.png
dark-theme: true
url: https://lachicadesistemas.github.io
twitter: alexiarsteinn
instagram: lachicadesistemas
github: alexiarstein
width: normal
plugins:
  - jeckyll-seo-tag
  - jeckyll-gist
  - jeckyll-feed
  - jemoji

show-author: true
animation: true
defaults:
  - scope:
      path: ""
      layout: "post"
    values:
    hidden: false
