remote_theme: sergiokopplin/indigo
#theme: jekyll-theme-minimal
title: Alexia
description: "Mi sitio tiquito"
email: alexiarstein@aol.com
external-image: false
picture: assets/images/alexia.jpg
dark-theme: true
url: https://lacahicadesistemas.github.io
twitter: alexiarsteinn
instagram: lachicadesistemas
github: alexiarstein
width: normal

