#theme: jekyll-theme-minimal
title: Alexia
description: "Mi sitio tiquito"
typing_text: Linux Geek Lady for 20 ish years.
email: alexiarstein@aol.com
github_username: alexiarstein
twitter_username: alexiarsteinn
remote_theme: longpdo/neumorphism
